GET http://localhost:3000/
Content-Type: application/json

###
GET http://localhost:3000/health
Content-Type: application/json

//Cái này để request từ json sang html
### 
POST http://localhost:3000/api/v1/json-html
Content-Type: application/json

{
  "tagName": "mjml",
  "attributes": {},
  "children": [
    {
      "tagName": "mj-head",
      "children": [
        {
          "tagName": "mj-html-attributes",
          "children": [
            {
              "tagName": "mj-selector",
              "attributes": {
                "path": ".custom"
              },
              "children": [
                {
                  "tagName": "mj-html-attribute",
                  "attributes": {
                    "name": "data-id"
                  },
                  "content": "42"
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "tagName": "mj-body",
      "attributes": {
        "width": "600px"
      },
      "children": [
        {
          "tagName": "mj-section",
          "attributes": {},
          "children": [
            {
              "tagName": "mj-column",
              "attributes": {},
              "children": [
                {
                  "tagName": "mj-image",
                  "attributes": {
                    "width": "100px",
                    "src": "/assets/img/logo-small.png"
                  }
                },
                {
                  "tagName": "mj-divider",
                  "attributes": {
                    "border-color": "#F46E43"
                  }
                },
                {
                  "tagName": "mj-text",
                  "attributes": {
                    "font-size": "20px",
                    "color": "#F45E43",
                    "font-family": "Helvetica",
                    "css-class": "custom",
                    "text-align": "center"
                  },
                  "content": "Hello World"
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}

//Cái này để request từ json sang mjml
### 
POST http://localhost:3000/api/v1/json-mjml
Content-Type: application/json

{
  "tagName": "mjml",
  "attributes": {},
  "children": [
    {
      "tagName": "mj-head",
      "children": [
        {
          "tagName": "mj-html-attributes",
          "children": [
            {
              "tagName": "mj-selector",
              "attributes": {
                "path": ".custom"
              },
              "children": [
                {
                  "tagName": "mj-html-attribute",
                  "attributes": {
                    "name": "data-id"
                  },
                  "content": "42"
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "tagName": "mj-body",
      "attributes": {
        "width": "600px"
      },
      "children": [
        {
          "tagName": "mj-section",
          "attributes": {},
          "children": [
            {
              "tagName": "mj-column",
              "attributes": {},
              "children": [
                {
                  "tagName": "mj-image",
                  "attributes": {
                    "width": "100px",
                    "src": "/assets/img/logo-small.png"
                  }
                },
                {
                  "tagName": "mj-divider",
                  "attributes": {
                    "border-color": "#F46E43"
                  }
                },
                {
                  "tagName": "mj-text",
                  "attributes": {
                    "font-size": "20px",
                    "color": "#F45E43",
                    "font-family": "Helvetica",
                    "css-class": "custom",
                    "text-align": "center"
                  },
                  "content": "Hello World"
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}

//Cái này từ mjml sang html
###
POST http://localhost:3000/api/v1/mjml-html
Content-Type: application/json

{
  "mjml": "<mjml><mj-head><mj-attributes><mj-text align=\"center\"/></mj-attributes></mj-head><mj-body width=\"600px\"><mj-section><mj-column><mj-image width=\"100px\" src=\"/assets/img/logo-small.png\"/><mj-divider border-color=\"#F46E43\"/><mj-text font-size=\"20px\" color=\"#F45E43\" font-family=\"Helvetica\" css-class=\"custom\" align=\"center\">Hello World</mj-text></mj-column></mj-section></mj-body></mjml>"
}
